### ISSUE TITLE
某些机型出现闪退情况

### ISSUE THREAD

**Issue by protectedMan** [DingProg/NetworkCaptureSelf#2]
复现机型：vivo x7 
系统版本：5.1.1 
报错时机：
进入app时首次调用网络请求就闪退，导致app无法使用（首屏都进不去）。
通过对照测试发现只要使用CaptureInfoInterceptor就会复现此问题。
报错堆栈：
![image](https://user-images.githubusercontent.com/17565737/80456834-d87a9780-8960-11ea-978a-d98735b28597.png)
`4-28 14:57:34.447 32379-32419 E/CrashReport: # LAUNCH TIME: 2020-04-28 14:57:33
04-28 14:57:34.447 32379-32419 E/CrashReport: # CRASH TYPE: JAVA_CATCH
04-28 14:57:34.447 32379-32419 E/CrashReport: # CRASH TIME: 2020-04-28 14:57:34
04-28 14:57:34.447 32379-32419 E/CrashReport: # CRASH PROCESS: com.zl.lezhu
04-28 14:57:34.447 32379-32419 E/CrashReport: # CRASH THREAD: RxCachedThreadScheduler-2
04-28 14:57:34.447 32379-32419 E/CrashReport: # REPORT ID: 21d445b4-187b-4dc5-a259-f38c03e8f3ad
04-28 14:57:34.447 32379-32419 E/CrashReport: # CRASH DEVICE: vivo X7 UNROOT
04-28 14:57:34.447 32379-32419 E/CrashReport: # RUNTIME AVAIL RAM:1246134272 ROM:30381637632 SD:29752492032
04-28 14:57:34.447 32379-32419 E/CrashReport: # RUNTIME TOTAL RAM:3752390656 ROM:57441845248 SD:56812699648
04-28 14:57:34.447 32379-32419 E/CrashReport: # CRASH STACK: 
04-28 14:57:34.447 32379-32419 E/CrashReport: io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | com.ding.library.internal.utils.CacheUtils
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:69)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.NoSuchMethodError: com.ding.library.internal.utils.CacheUtils
        at com.ding.library.CaptureInfoInterceptor.intercept(CaptureInfoInterceptor.java:159)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.lezhu.common.http.InterceptorUtil$2.intercept(InterceptorUtil.java:109)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at ren.yale.android.retrofitcachelibrx2.intercept.MockInterceptor.intercept(MockInterceptor.java:29)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
        at okhttp3.RealCall.execute(RealCall.java:92)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:186)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:45)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
04-28 14:57:34.447 32379-32419 E/CrashReport: #++++++++++++++++++++++++++++++++++++++++++#
04-28 14:57:34.447 32379-32417 E/CrashReport: #++++++++++Record By Bugly++++++++++#
04-28 14:57:34.447 32379-32417 E/CrashReport: # You can use Bugly(http:\\bugly.qq.com) to get more Crash Detail!
04-28 14:57:34.447 32379-32417 E/CrashReport: # PKG NAME: com.zl.lezhu
04-28 14:57:34.447 32379-32417 E/CrashReport: # APP VER: 6.3.0_beta(2020042814)
04-28 14:57:34.447 32379-32417 E/CrashReport: # LAUNCH TIME: 2020-04-28 14:57:33
04-28 14:57:34.447 32379-32417 E/CrashReport: # CRASH TYPE: JAVA_CATCH
04-28 14:57:34.447 32379-32417 E/CrashReport: # CRASH TIME: 2020-04-28 14:57:34
04-28 14:57:34.447 32379-32417 E/CrashReport: # CRASH PROCESS: com.zl.lezhu
04-28 14:57:34.447 32379-32417 E/CrashReport: # CRASH THREAD: RxCachedThreadScheduler-1
04-28 14:57:34.447 32379-32417 E/CrashReport: # REPORT ID: 73900366-6907-451e-822c-77b874b56232
04-28 14:57:34.447 32379-32417 E/CrashReport: # CRASH DEVICE: vivo X7 UNROOT
04-28 14:57:34.447 32379-32417 E/CrashReport: # RUNTIME AVAIL RAM:1246642176 ROM:30381645824 SD:29752500224
04-28 14:57:34.447 32379-32417 E/CrashReport: # RUNTIME TOTAL RAM:3752390656 ROM:57441845248 SD:56812699648
04-28 14:57:34.447 32379-32417 E/CrashReport: # CRASH STACK: 
04-28 14:57:34.447 32379-32417 E/CrashReport: io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | com.ding.library.internal.utils.CacheUtils
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:69)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.NoSuchMethodError: com.ding.library.internal.utils.CacheUtils
        at com.ding.library.CaptureInfoInterceptor.intercept(CaptureInfoInterceptor.java:159)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.lezhu.common.http.InterceptorUtil$2.intercept(InterceptorUtil.java:109)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at ren.yale.android.retrofitcachelibrx2.intercept.MockInterceptor.intercept(MockInterceptor.java:29)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
        at okhttp3.RealCall.execute(RealCall.java:92)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:186)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:45)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
04-28 14:57:34.447 32379-32417 E/CrashReport: #++++++++++++++++++++++++++++++++++++++++++#
04-28 14:57:34.447 32379-32502 E/setErrorHandler:: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | com.ding.library.internal.utils.CacheUtils
04-28 14:57:34.447 32379-32418 E/CrashReport: Java Catch Happen
04-28 14:57:34.447 32379-32418 E/CrashReport: stack frame :9, has cause true
04-28 14:57:34.457 32379-32503 E/setErrorHandler:: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | com.ding.library.internal.utils.CacheUtils
04-28 14:57:34.457 32379-32418 E/CrashReport: #++++++++++Record By Bugly++++++++++#
04-28 14:57:34.457 32379-32418 E/CrashReport: # You can use Bugly(http:\\bugly.qq.com) to get more Crash Detail!
04-28 14:57:34.457 32379-32418 E/CrashReport: # PKG NAME: com.zl.lezhu
04-28 14:57:34.457 32379-32418 E/CrashReport: # APP VER: 6.3.0_beta(2020042814)
04-28 14:57:34.457 32379-32418 E/CrashReport: # LAUNCH TIME: 2020-04-28 14:57:33
04-28 14:57:34.457 32379-32418 E/CrashReport: # CRASH TYPE: JAVA_CATCH
04-28 14:57:34.457 32379-32418 E/CrashReport: # CRASH TIME: 2020-04-28 14:57:34
04-28 14:57:34.457 32379-32418 E/CrashReport: # CRASH PROCESS: com.zl.lezhu
04-28 14:57:34.457 32379-32418 E/CrashReport: # CRASH THREAD: RxCachedThreadScheduler-3
04-28 14:57:34.457 32379-32418 E/CrashReport: # REPORT ID: e28c0be4-95f7-450a-b7ae-2b67f20e4888
04-28 14:57:34.457 32379-32418 E/CrashReport: # CRASH DEVICE: vivo X7 UNROOT
04-28 14:57:34.457 32379-32418 E/CrashReport: # RUNTIME AVAIL RAM:1244311552 ROM:30381629440 SD:29752483840
04-28 14:57:34.457 32379-32418 E/CrashReport: # RUNTIME TOTAL RAM:3752390656 ROM:57441845248 SD:56812699648
04-28 14:57:34.457 32379-32418 E/CrashReport: # CRASH STACK: 
04-28 14:57:34.457 32379-32418 E/CrashReport: io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | com.ding.library.internal.utils.CacheUtils
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:69)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.NoSuchMethodError: com.ding.library.internal.utils.CacheUtils
        at com.ding.library.CaptureInfoInterceptor.intercept(CaptureInfoInterceptor.java:159)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.lezhu.common.http.InterceptorUtil$2.intercept(InterceptorUtil.java:109)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at ren.yale.android.retrofitcachelibrx2.intercept.MockInterceptor.intercept(MockInterceptor.java:29)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
        at okhttp3.RealCall.execute(RealCall.java:92)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:186)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:45)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
04-28 14:57:34.457 32379-32418 E/CrashReport: #++++++++++++++++++++++++++++++++++++++++++#
04-28 14:57:34.487 32379-32417 E/CrashReport: Java Catch Happen
04-28 14:57:34.497 32379-32417 E/CrashReport: stack frame :9, has cause true
04-28 14:57:34.507 32379-32417 E/CrashReport: #++++++++++Record By Bugly++++++++++#
04-28 14:57:34.507 32379-32417 E/CrashReport: # You can use Bugly(http:\\bugly.qq.com) to get more Crash Detail!
04-28 14:57:34.507 32379-32417 E/CrashReport: # PKG NAME: com.zl.lezhu
04-28 14:57:34.507 32379-32417 E/CrashReport: # APP VER: 6.3.0_beta(2020042814)
04-28 14:57:34.507 32379-32417 E/CrashReport: # LAUNCH TIME: 2020-04-28 14:57:33
04-28 14:57:34.507 32379-32417 E/CrashReport: # CRASH TYPE: JAVA_CATCH
04-28 14:57:34.507 32379-32417 E/CrashReport: # CRASH TIME: 2020-04-28 14:57:34
04-28 14:57:34.507 32379-32417 E/CrashReport: # CRASH PROCESS: com.zl.lezhu
04-28 14:57:34.507 32379-32417 E/CrashReport: # CRASH THREAD: RxCachedThreadScheduler-4
04-28 14:57:34.507 32379-32417 E/CrashReport: # REPORT ID: c958ed91-6c4d-427f-9f6c-90d964501b67
04-28 14:57:34.507 32379-32417 E/CrashReport: # CRASH DEVICE: vivo X7 UNROOT
04-28 14:57:34.507 32379-32417 E/CrashReport: # RUNTIME AVAIL RAM:1235259392 ROM:30381404160 SD:29752258560
04-28 14:57:34.507 32379-32417 E/CrashReport: # RUNTIME TOTAL RAM:3752390656 ROM:57441845248 SD:56812699648
04-28 14:57:34.507 32379-32417 E/CrashReport: # CRASH STACK: 
04-28 14:57:34.507 32379-32417 E/CrashReport: io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | com.ding.library.internal.utils.CacheUtils
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:69)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.NoSuchMethodError: com.ding.library.internal.utils.CacheUtils
        at com.ding.library.CaptureInfoInterceptor.intercept(CaptureInfoInterceptor.java:159)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.lezhu.common.http.InterceptorUtil$2.intercept(InterceptorUtil.java:109)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at ren.yale.android.retrofitcachelibrx2.intercept.MockInterceptor.intercept(MockInterceptor.java:29)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
        at okhttp3.RealCall.execute(RealCall.java:92)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:186)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:45)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
04-28 14:57:34.507 32379-32417 E/CrashReport: #++++++++++++++++++++++++++++++++++++++++++#
04-28 14:57:34.577 32379-32492 E/CrashReport: sys default last handle start!
04-28 14:57:34.577 32379-32492 E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.zl.lezhu, PID: 32379
    java.lang.NoSuchMethodError: No virtual method checkSelfPermission(Ljava/lang/String;)I in class Landroid/content/Context; or its super classes (declaration of 'android.content.Context' appears in /system/framework/framework.jar)
        at com.ding.library.internal.utils.CacheUtils.<init>(CacheUtils.java:40)
        at com.ding.library.internal.utils.CacheUtils.<clinit>(CacheUtils.java:28)
        at com.ding.library.CaptureInfoInterceptor.intercept(CaptureInfoInterceptor.java:159)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.lezhu.common.http.InterceptorUtil$2.intercept(InterceptorUtil.java:109)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at ren.yale.android.retrofitcachelibrx2.intercept.MockInterceptor.intercept(MockInterceptor.java:29)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:200)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)`

**Comment by DingProg** [comment]
```
java.lang.NoSuchMethodError: No virtual method checkSelfPermission(Ljava/lang/String;)
```
看崩溃是检查权限那个方法不存在，可能系统版本不支持, [代码](https://github.com/DingProg/NetworkCaptureSelf/blob/master/library/src/main/java/com/ding/library/internal/utils/CacheUtils.java)
```java
context.checkSelfPermission()  //不存在
```
修复方法，一般建议使用
```java
ActivityCompat.checkSelfPermission(context,权限)
```

# 问题已经修复，建议使用版本
```java
	dependencies {
	        implementation 'com.github.DingProg:NetworkCaptureSelf:v1.0.2'
	}
```
